# Generated by Django 3.1.4 on 2020-12-16 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 29, 4, 766358))),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
